//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordAstroBot.Simbad {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SIMBADSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SIMBADSettings defaultInstance = ((SIMBADSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SIMBADSettings())));
        
        public static SIMBADSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("output console=off script=off\r\nformat object f1 \"[[Main_id]]\\n%IDLIST(1)\\n\" +\r\n\"[" +
            "[ObjectType]]\\n%OTYPE(V)\\n\" +\r\n\"[[Coordinates]]\\nRA: %COO(A)\\nDEC: %COO(D)\\n\" +\r" +
            "\n\"[[Identifiers]]\\n%IDLIST[%-20*\\n]\"+\r\n\"\"\r\nquery id {0}\r\n")]
        public string ObjectQuery {
            get {
                return ((string)(this["ObjectQuery"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Identifier not found in the database")]
        public string IdentifierNotFoundMessage {
            get {
                return ((string)(this["IdentifierNotFoundMessage"]));
            }
            set {
                this["IdentifierNotFoundMessage"] = value;
            }
        }
    }
}
