//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordAstroBot.Simbad {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.0.0")]
    internal sealed partial class SIMBADSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SIMBADSettings defaultInstance = ((SIMBADSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SIMBADSettings())));
        
        public static SIMBADSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"output console=off script=off
format object f1 ""[[Main_id]]\n%IDLIST(1)\n"" +
""[[ObjectType]]\n%OTYPE(V)\n"" +
""[[Coordinates]]\nRA: %COO(A)\nDEC: %COO(D)\n"" +
""[[Identifiers]]\n%IDLIST[%-20*\n]\n""+
""[[OtherTypes]]\n%OTYPELIST(V\n)\n""+
""[[ProperMotion]]\nRA: %PM(A)\nDEC: %PM(D)\n"" +
""[[Parallax]]\nValue: %PLX(V)\nError: %PLX(E)\n"" +
""[[RadialVelocity]]\nz: %RV(Z)\nError: %RV(E)\nv: %RV(V)\n"" +
""[[Distances]]\n%MEASLIST(distance)\n"" +
""[[Fluxes]]\n%FLUXLIST()[%*(N=F)\n]\n"" +
""[[end]]""
query id {0}
")]
        public string ObjectQuery {
            get {
                return ((string)(this["ObjectQuery"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Identifier not found in the database")]
        public string IdentifierNotFoundMessage {
            get {
                return ((string)(this["IdentifierNotFoundMessage"]));
            }
            set {
                this["IdentifierNotFoundMessage"] = value;
            }
        }
    }
}
